### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by luisgerhorst** [webdevops/go-prometheus-common#5]
Would it be possible to clarify the license of this repository? Preferably in a  machine-readable format.

**Comment by mattdurham** [comment]
+1 to this. Would def appreciate this. @luisgerhorst brought up https://github.com/grafana/agent/issues/4130 and having a license makes usage of this library a lot clearer.

**Comment by luisgerhorst** [comment]
Thanks @mblaschke!
